In [5]:
from tensorflow import keras
import tensorflow as tf
k = keras.backend

In [6]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [7]:
t.dtype

tf.float32

In [13]:
print(t[:,1])

tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [17]:
print(t[...,1])
print(t[...,2,tf.newaxis])
# shape difference

tf.Tensor([2. 5.], shape=(2,), dtype=float32)
tf.Tensor(
[[3.]
 [6.]], shape=(2, 1), dtype=float32)


In [19]:
print(tf.add(t,10))

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)


In [20]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [25]:
tf.square(t)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [26]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [27]:
tf.matmul(t,tf.transpose(t))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

## type conversions

In [30]:
a = tf.constant(19.,dtype = tf.float64)
b = tf.constant(21.)
print(b + tf.cast(a,tf.float32))

tf.Tensor(40.0, shape=(), dtype=float32)


In [34]:
c = a - 10
print(c)

tf.Tensor(9.0, shape=(), dtype=float64)


In [32]:
a

<tf.Tensor: shape=(), dtype=float64, numpy=19.0>

In [33]:
print(a)

tf.Tensor(19.0, shape=(), dtype=float64)


## Variables

In [39]:
v = tf.Variable([[1,2,3],[4,5,6]],dtype = tf.float32)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [40]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [42]:
 v[:,2].assign(42.)   

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4., 42.],
       [ 8., 10., 42.]], dtype=float32)>

In [43]:
v[:,0].assign(v[:,2])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[42.,  4., 42.],
       [42., 10., 42.]], dtype=float32)>

In [48]:
v.scatter_nd_update(indices = [[0,0],[1,2]],updates = [10.,10.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[10.,  4., 42.],
       [42., 10., 10.]], dtype=float32)>

## Other data structures

- sparse tensors - tf.SparseTensor() - efficiently represents the tensors containg 0s
- Tensor arrays = tf.TensorArray() - list of tensors - all tensors they store should be of same shape and dtype
- Ragged Tensors = tf.RaggedTensor() - static list of list of tensors
- string Tensors - tf.StringTensor() - 